#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require 'active_support'
require "mailman"

Mailman.config.pop3 = {
  server: 'pop.gmail.com', port: 995, ssl: true,
  username: 'loquaciousbuzz@gmail.com',
  password: 'L0quacious3uzz'
}

Mailman::Application.run do 
  default do 
    parser = EmailParser.new(message)
    Bookmark.create_through_email(parser.user_email, parser.tags, parser.url)
  end
end


